version: '3.8'
services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.15
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - "8000:8000"
    volumes:
      - chroma_dev_data:/chroma/chroma/
volumes:
  chroma_dev_data:
    driver: local