services:
  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - DB_URL=${DB_URL:jdbc:mysql://localhost:3306/shopshopday_db}
      - DB_USERNAME=${DB_USERNAME:root}
      - DB_PASSWORD=${DB_PASSWORD:a25138363a}
      - JWT_SECRET=${JWT_SECRET:test_secret}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION:300000}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:2592000000}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:test_key}
      - OPENAI_API_KEY=${OPENAI_API_KEY:test_key}
      - CHROMA_HOST=${CHROMA_HOST:http://localhost}
      - CHROMA_PORT=${CHROMA_PORT:8000}
    depends_on:
      db:
        condition: service_healthy
      chromadb:
        condition: service_started

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_URL:jdbc:mysql://localhost:3306/shopshopday_db}
      - MYSQL_USER=${DB_USERNAME:root}
      - MYSQL_PASSWORD=${DB_PASSWORD:a25138363a}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 10s

  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.15
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma/

volumes:
  mysql_data:
    driver: local
  chroma-data:
    driver: local
